version: "{build}"
shallow_clone: true
clone_folder: c:\gopath\src\github.com\sourcegraph\go-langserver
environment:
  GOPATH: c:\gopath
install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - git clone https://github.com/alexsaveliev/ctxvfs --branch windows --single-branch c:\gopath\src\github.com\sourcegraph\ctxvfs  
  - go get -d -t ./...
  - go test -i ./...
build_script:
  - go test -race -v ./...
