version: "{build}"
shallow_clone: true
clone_folder: c:\gopath\src\github.com\sourcegraph\go-langserver
environment:
  GOPATH: c:\gopath
install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t ./...
  - go get -v gopkg.in/inconshreveable/log15.v2
build_script:
  - go test -v ./...
